# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce25d72a3f17d691682894db16e9d82bf420fad49dc0df003d19d8f62fe83c9311bc7d5a903ab590cdd02d58e3826f3fe1e9648aefbbc42d145b7b5ffe8c6996

test:
  secret_key_base: 24058a8d741204f1479f1c10404819c78f058bcba3fb23fef9c7969a4b7a61c0fb439a72cf63d796fa51d52f07af3f7522c477a2be483e98e63b21238bc444de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
